// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVSWlmQHoWOCIP6YSzB7LCDwBN7aBixA',
    appId: '1:819710750483:web:a5888c2f61b13ff3c374e6',
    messagingSenderId: '819710750483',
    projectId: 'mobile-3b885',
    authDomain: 'mobile-3b885.firebaseapp.com',
    storageBucket: 'mobile-3b885.appspot.com',
    measurementId: 'G-7P3DXDRCSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1YTM2iGS9Zr6af6otNEkx3tMQ6Tf_75c',
    appId: '1:819710750483:android:48092a841b1563e8c374e6',
    messagingSenderId: '819710750483',
    projectId: 'mobile-3b885',
    storageBucket: 'mobile-3b885.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNZfpnGPu5aFivG3pFe84DV6OFtVfWf9o',
    appId: '1:819710750483:ios:f182cbe860a50817c374e6',
    messagingSenderId: '819710750483',
    projectId: 'mobile-3b885',
    storageBucket: 'mobile-3b885.appspot.com',
    iosBundleId: 'com.carrental.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNZfpnGPu5aFivG3pFe84DV6OFtVfWf9o',
    appId: '1:819710750483:ios:f182cbe860a50817c374e6',
    messagingSenderId: '819710750483',
    projectId: 'mobile-3b885',
    storageBucket: 'mobile-3b885.appspot.com',
    iosBundleId: 'com.carrental.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZVSWlmQHoWOCIP6YSzB7LCDwBN7aBixA',
    appId: '1:819710750483:web:6dde4df2ea64bcccc374e6',
    messagingSenderId: '819710750483',
    projectId: 'mobile-3b885',
    authDomain: 'mobile-3b885.firebaseapp.com',
    storageBucket: 'mobile-3b885.appspot.com',
    measurementId: 'G-K3GYVGE7VF',
  );
}
